/* eslint-disable */
// AUTO-GENERATED by tools/audio/sync-studio-audio.mjs. Do not edit by hand.
// Candidates awaiting approval. Required only under __DEV__ (never bundled in release).
// Source: ../audio (10 folders, 0 cues)
import type { BedDef, CueDef } from '../../../gamekit/audio/chrisBank';

export const STUDIO_CUES: Record<string, Record<string, CueDef>> = {

};

export const STUDIO_BEDS: Record<string, Record<string, BedDef>> = {

};
