/* eslint-disable */
// AUTO-GENERATED by tools/audio/sync-studio-audio.mjs. Do not edit by hand.
// Approved by Dustin (by ear). These ship.
// Source: ../audio (10 folders, 361 cues)
import type { BedDef, CueDef } from '../../../gamekit/audio/chrisBank';

export const STUDIO_CUES: Record<string, Record<string, CueDef>> = {

};

export const STUDIO_BEDS: Record<string, Record<string, BedDef>> = {

};

export const STUDIO_AUDIO_SYNCED = {"at":"2026-09-30T17:54:50Z","games":10,"cues":361};
