// Generated by tools/fx/kit-art.cjs from src/fx/kit.json. Do not edit by hand.
/* eslint-disable */
export const KIT_ART: Record<string, number> = {
  'bubble-wand.webp': require('../../../assets/fx/bubble-wand.webp'),
  'bubble.webp': require('../../../assets/fx/bubble.webp'),
  'bulb-gold.webp': require('../../../assets/fx/bulb-gold.webp'),
  'bulb-green.webp': require('../../../assets/fx/bulb-green.webp'),
  'bulb-red.webp': require('../../../assets/fx/bulb-red.webp'),
  'dragon-body.webp': require('../../../assets/fx/dragon-body.webp'),
  'dragon-puff.webp': require('../../../assets/fx/dragon-puff.webp'),
  'dragon-wing.webp': require('../../../assets/fx/dragon-wing.webp'),
  'gift-mini.webp': require('../../../assets/fx/gift-mini.webp'),
  'globe-base.webp': require('../../../assets/fx/globe-base.webp'),
  'globe-glass.webp': require('../../../assets/fx/globe-glass.webp'),
  'glow.webp': require('../../../assets/fx/glow.webp'),
  'mini-bat.webp': require('../../../assets/fx/mini-bat.webp'),
  'plaid-backpack.webp': require('../../../assets/fx/plaid-backpack.webp'),
  'snowflake.webp': require('../../../assets/fx/snowflake.webp'),
  'snowglobe-backdrop.webp': require('../../../assets/fx/snowglobe-backdrop.webp'),
  'spark.webp': require('../../../assets/fx/spark.webp'),
  'swirl-specs.webp': require('../../../assets/fx/swirl-specs.webp'),
  'swirl.webp': require('../../../assets/fx/swirl.webp'),
};
