'use strict';
/**
 * SIM_VERSION = first 12 hex of sha256(core.ts). Every balance change to the
 * sim changes the version, and the server keeps verifiers for the last 3.
 *   node tools/sharky/sim-version.cjs         writes sim/version.generated.ts
 *   node tools/sharky/sim-version.cjs --check exits 1 when stale
 */
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const root = path.resolve(__dirname, '../..');
const core = path.join(root, 'src/games/sharky/sim/core.ts');
const out = path.join(root, 'src/games/sharky/sim/version.generated.ts');
function version() {
  return crypto.createHash('sha256').update(fs.readFileSync(core)).digest('hex').slice(0, 12);
}
const text = (v) => `// AUTO-GENERATED by tools/sharky/sim-version.cjs from sim/core.ts. Do not edit.\nexport const SIM_VERSION = 'swim-${v}';\n`;
module.exports = { version, text, out };
if (require.main === module) {
  const v = version();
  if (process.argv.includes('--check')) {
    const cur = fs.existsSync(out) ? fs.readFileSync(out, 'utf8') : '';
    if (cur !== text(v)) { console.error('sim/version.generated.ts is stale: run node tools/sharky/sim-version.cjs'); process.exit(1); }
    console.log('SIM_VERSION ok', v);
  } else {
    fs.writeFileSync(out, text(v));
    console.log('SIM_VERSION', v);
  }
}
