/**
 * Dev-only Stamp Book preview (EXPO_PUBLIC_STAMP_BOOK_PREVIEW=1): a mixed book
 * of earned, claimable, in-progress, locked and secret stamps for visual checks.
 * Art: set EXPO_PUBLIC_STAMP_ART_BASE to a folder of <slug>.png files.
 */
import type { StampData, StampsResponse } from '../../api/endpoints/me/stamps';
import { FALLBACK_SECTIONS } from './model';

const STAMPS: StampData[] = [
 {
  "id": 900,
  "slug": "region-magic-kingdom",
  "name": "Magic Kingdom",
  "category": "parks",
  "goal": "Visit Magic Kingdom with the app open",
  "metric": "visited_magic_kingdom",
  "target_value": 1,
  "rarity": "common",
  "image_key": null,
  "emoji": null,
  "is_hidden": false,
  "sort_order": 0,
  "progress": 1,
  "target": 1,
  "progress_percentage": 100,
  "progress_text": "1/1",
  "is_earned": true,
  "earned_at": "2026-09-27T15:12:00Z",
  "reward_claimed": true,
  "rewards": {
   "energy": 0,
   "tickets": 5,
   "xp": 100,
   "coins": 0,
   "title": null
  },
  "section": "parks",
  "icon_url": null,
  "how_to": "Go to Magic Kingdom!",
  "short_name": "Magic Kingdom"
 },
 {
  "id": 901,
  "slug": "region-epic-universe",
  "name": "Epic Universe",
  "category": "parks",
  "goal": "Visit Epic Universe with the app open",
  "metric": "visited_epic_universe",
  "target_value": 1,
  "rarity": "rare",
  "image_key": null,
  "emoji": null,
  "is_hidden": false,
  "sort_order": 1,
  "progress": 1,
  "target": 1,
  "progress_percentage": 100,
  "progress_text": "1/1",
  "is_earned": true,
  "earned_at": "2026-09-30T18:40:00Z",
  "reward_claimed": false,
  "rewards": {
   "energy": 0,
   "tickets": 15,
   "xp": 250,
   "coins": 0,
   "title": null
  },
  "section": "parks",
  "icon_url": null,
  "how_to": "Go to Epic Universe!",
  "short_name": "Epic Universe"
 },
 {
  "id": 902,
  "slug": "region-islands-of-adventure",
  "name": "Islands of Adventure",
  "category": "parks",
  "goal": "Visit Islands of Adventure with the app open",
  "metric": "visited_islands_of_adventure",
  "target_value": 1,
  "rarity": "uncommon",
  "image_key": null,
  "emoji": null,
  "is_hidden": false,
  "sort_order": 2,
  "progress": 1,
  "target": 1,
  "progress_percentage": 100,
  "progress_text": "1/1",
  "is_earned": true,
  "earned_at": "2026-09-29T16:05:00Z",
  "reward_claimed": true,
  "rewards": {
   "energy": 0,
   "tickets": 8,
   "xp": 150,
   "coins": 0,
   "title": null
  },
  "section": "parks",
  "icon_url": null,
  "how_to": "Go to Islands of Adventure!",
  "short_name": "Islands of Adventure"
 },
 {
  "id": 903,
  "slug": "region-volcano-bay",
  "name": "Volcano Bay",
  "category": "parks",
  "goal": "Visit Volcano Bay with the app open",
  "metric": "visited_volcano_bay",
  "target_value": 1,
  "rarity": "uncommon",
  "image_key": null,
  "emoji": null,
  "is_hidden": false,
  "sort_order": 3,
  "progress": 0,
  "target": 1,
  "progress_percentage": 0,
  "progress_text": "0/1",
  "is_earned": false,
  "earned_at": null,
  "reward_claimed": false,
  "rewards": {
   "energy": 0,
   "tickets": 8,
   "xp": 150,
   "coins": 0,
   "title": null
  },
  "section": "parks",
  "icon_url": null,
  "how_to": "Go to Volcano Bay!",
  "short_name": "Volcano Bay"
 },
 {
  "id": 904,
  "slug": "region-disneyland",
  "name": "Disneyland",
  "category": "parks",
  "goal": "Visit Disneyland with the app open",
  "metric": "visited_disneyland",
  "target_value": 1,
  "rarity": "common",
  "image_key": null,
  "emoji": null,
  "is_hidden": false,
  "sort_order": 4,
  "progress": 0,
  "target": 1,
  "progress_percentage": 0,
  "progress_text": "0/1",
  "is_earned": false,
  "earned_at": null,
  "reward_claimed": false,
  "rewards": {
   "energy": 0,
   "tickets": 5,
   "xp": 100,
   "coins": 0,
   "title": null
  },
  "section": "parks",
  "icon_url": null,
  "how_to": "Go to Disneyland!",
  "short_name": "Disneyland"
 },
 {
  "id": 905,
  "slug": "explorer",
  "name": "Explorer",
  "category": "parks",
  "goal": "Visit 2 different parks",
  "metric": "parks_visited",
  "target_value": 2,
  "rarity": "uncommon",
  "image_key": null,
  "emoji": null,
  "is_hidden": false,
  "sort_order": 5,
  "progress": 2,
  "target": 2,
  "progress_percentage": 100,
  "progress_text": "2/2",
  "is_earned": true,
  "earned_at": "2026-09-29T16:05:00Z",
  "reward_claimed": true,
  "rewards": {
   "energy": 30,
   "tickets": 5,
   "xp": 250,
   "coins": 0,
   "title": "Explorer"
  },
  "section": "parks",
  "icon_url": null,
  "how_to": "Visit 2 different parks",
  "short_name": "Explorer"
 },
 {
  "id": 906,
  "slug": "park-hopper",
  "name": "Hop Star",
  "category": "parks",
  "goal": "Visit 5 different parks",
  "metric": "parks_visited",
  "target_value": 5,
  "rarity": "rare",
  "image_key": null,
  "emoji": null,
  "is_hidden": false,
  "sort_order": 6,
  "progress": 3,
  "target": 5,
  "progress_percentage": 60,
  "progress_text": "3/5",
  "is_earned": false,
  "earned_at": null,
  "reward_claimed": false,
  "rewards": {
   "energy": 100,
   "tickets": 20,
   "xp": 750,
   "coins": 0,
   "title": "Hop Star"
  },
  "section": "parks",
  "icon_url": null,
  "how_to": "Visit 5 different parks",
  "short_name": "Hop Star"
 },
 {
  "id": 907,
  "slug": "ride-passport-magic-kingdom",
  "name": "Magic Kingdom Ride Passport",
  "category": "parks",
  "goal": "Complete the current Magic Kingdom ride coin collection",
  "metric": "ride_passport_magic_kingdom",
  "target_value": 100,
  "rarity": "legendary",
  "image_key": null,
  "emoji": null,
  "is_hidden": false,
  "sort_order": 7,
  "progress": 40,
  "target": 100,
  "progress_percentage": 40,
  "progress_text": "40/100",
  "is_earned": false,
  "earned_at": null,
  "reward_claimed": false,
  "rewards": {
   "energy": 150,
   "tickets": 20,
   "xp": 1500,
   "coins": 0,
   "title": "Kingdom Ride Master"
  },
  "section": "parks",
  "icon_url": null,
  "how_to": "Get every MK ride coin",
  "short_name": "MK Ride Passport"
 },
 {
  "id": 908,
  "slug": "first-steps",
  "name": "First Steps",
  "category": "hunt",
  "goal": "Catch your first find on the map",
  "metric": "prep_items_collected",
  "target_value": 1,
  "rarity": "common",
  "image_key": null,
  "emoji": null,
  "is_hidden": false,
  "sort_order": 8,
  "progress": 1,
  "target": 1,
  "progress_percentage": 100,
  "progress_text": "1/1",
  "is_earned": true,
  "earned_at": "2026-09-26T19:00:00Z",
  "reward_claimed": true,
  "rewards": {
   "energy": 0,
   "tickets": 0,
   "xp": 50,
   "coins": 0,
   "title": null
  },
  "section": "hunt",
  "icon_url": null,
  "how_to": "Catch your first find",
  "short_name": "First Steps"
 },
 {
  "id": 909,
  "slug": "treasure-hunter",
  "name": "Treasure Hunter",
  "category": "hunt",
  "goal": "Catch 25 finds on the map",
  "metric": "prep_items_collected",
  "target_value": 25,
  "rarity": "uncommon",
  "image_key": null,
  "emoji": null,
  "is_hidden": false,
  "sort_order": 9,
  "progress": 14,
  "target": 25,
  "progress_percentage": 56,
  "progress_text": "14/25",
  "is_earned": false,
  "earned_at": null,
  "reward_claimed": false,
  "rewards": {
   "energy": 50,
   "tickets": 10,
   "xp": 500,
   "coins": 0,
   "title": null
  },
  "section": "hunt",
  "icon_url": null,
  "how_to": "Catch 25 finds",
  "short_name": "Treasure Hunter"
 },
 {
  "id": 910,
  "slug": "deep-dive",
  "name": "Deep Dive",
  "category": "hunt",
  "goal": "Catch 50 finds on the map",
  "metric": "prep_items_collected",
  "target_value": 50,
  "rarity": "rare",
  "image_key": null,
  "emoji": null,
  "is_hidden": false,
  "sort_order": 10,
  "progress": 14,
  "target": 50,
  "progress_percentage": 28,
  "progress_text": "14/50",
  "is_earned": false,
  "earned_at": null,
  "reward_claimed": false,
  "rewards": {
   "energy": 75,
   "tickets": 10,
   "xp": 500,
   "coins": 0,
   "title": null
  },
  "section": "hunt",
  "icon_url": null,
  "how_to": "Catch 50 finds",
  "short_name": "Deep Dive"
 },
 {
  "id": 911,
  "slug": "wild-legend-finder",
  "name": "Wild Legend Finder",
  "category": "hunt",
  "goal": "Catch two different legendary finds",
  "metric": "wild_legendary_variants",
  "target_value": 2,
  "rarity": "legendary",
  "image_key": null,
  "emoji": null,
  "is_hidden": false,
  "sort_order": 11,
  "progress": 2,
  "target": 2,
  "progress_percentage": 100,
  "progress_text": "2/2",
  "is_earned": true,
  "earned_at": "2026-10-01T22:10:00Z",
  "reward_claimed": false,
  "rewards": {
   "energy": 0,
   "tickets": 0,
   "xp": 300,
   "coins": 0,
   "title": "Wild Legend"
  },
  "section": "hunt",
  "icon_url": null,
  "how_to": "Catch 2 legendary finds",
  "short_name": "Wild Legend"
 },
 {
  "id": 912,
  "slug": "set-collector",
  "name": "Set Collector",
  "category": "hunt",
  "goal": "Finish any collection set",
  "metric": "sets_completed",
  "target_value": 1,
  "rarity": "uncommon",
  "image_key": null,
  "emoji": null,
  "is_hidden": false,
  "sort_order": 12,
  "progress": 0,
  "target": 1,
  "progress_percentage": 0,
  "progress_text": "0/1",
  "is_earned": false,
  "earned_at": null,
  "reward_claimed": false,
  "rewards": {
   "energy": 50,
   "tickets": 10,
   "xp": 300,
   "coins": 0,
   "title": null
  },
  "section": "hunt",
  "icon_url": null,
  "how_to": "Finish a collection set",
  "short_name": "Set Collector"
 },
 {
  "id": 913,
  "slug": "mystery-stamp",
  "name": "???",
  "category": "hunt",
  "goal": "Keep hunting. This one finds you.",
  "metric": "prep_items_collected",
  "target_value": 100,
  "rarity": "legendary",
  "image_key": null,
  "emoji": null,
  "is_hidden": true,
  "sort_order": 13,
  "progress": 14,
  "target": 100,
  "progress_percentage": 14,
  "progress_text": "14/100",
  "is_earned": false,
  "earned_at": null,
  "reward_claimed": false,
  "rewards": {
   "energy": 200,
   "tickets": 50,
   "xp": 2000,
   "coins": 5000,
   "title": "Legendary Explorer"
  },
  "section": "hunt",
  "icon_url": null,
  "how_to": "Keep hunting!",
  "short_name": "???",
  "secret_hint": "A mountain of finds hides this one!"
 },
 {
  "id": 914,
  "slug": "first-ride-coin",
  "name": "First Ride Coin",
  "category": "rides",
  "goal": "Collect your first ride coin",
  "metric": "park_coins_collected",
  "target_value": 1,
  "rarity": "common",
  "image_key": null,
  "emoji": null,
  "is_hidden": false,
  "sort_order": 14,
  "progress": 1,
  "target": 1,
  "progress_percentage": 100,
  "progress_text": "1/1",
  "is_earned": true,
  "earned_at": "2026-09-27T15:30:00Z",
  "reward_claimed": true,
  "rewards": {
   "energy": 10,
   "tickets": 0,
   "xp": 50,
   "coins": 0,
   "title": null
  },
  "section": "rides",
  "icon_url": null,
  "how_to": "Get your first ride coin",
  "short_name": "First Ride Coin"
 },
 {
  "id": 915,
  "slug": "ride-coin-collector",
  "name": "Ride Coin Collector",
  "category": "rides",
  "goal": "Collect five different ride coins",
  "metric": "park_coins_collected",
  "target_value": 5,
  "rarity": "rare",
  "image_key": null,
  "emoji": null,
  "is_hidden": false,
  "sort_order": 15,
  "progress": 3,
  "target": 5,
  "progress_percentage": 60,
  "progress_text": "3/5",
  "is_earned": false,
  "earned_at": null,
  "reward_claimed": false,
  "rewards": {
   "energy": 0,
   "tickets": 0,
   "xp": 250,
   "coins": 0,
   "title": "Coin Collector"
  },
  "section": "rides",
  "icon_url": null,
  "how_to": "Get 5 different ride coins",
  "short_name": "Coin Collector"
 },
 {
  "id": 916,
  "slug": "queue-navigator",
  "name": "Queue Navigator",
  "category": "rides",
  "goal": "Play 10 minutes of LinePlay in one ride line",
  "metric": "verified_lineplay_sessions",
  "target_value": 1,
  "rarity": "uncommon",
  "image_key": null,
  "emoji": null,
  "is_hidden": false,
  "sort_order": 16,
  "progress": 0,
  "target": 1,
  "progress_percentage": 0,
  "progress_text": "0/1",
  "is_earned": false,
  "earned_at": null,
  "reward_claimed": false,
  "rewards": {
   "energy": 20,
   "tickets": 0,
   "xp": 75,
   "coins": 0,
   "title": "Queue Navigator"
  },
  "section": "rides",
  "icon_url": null,
  "how_to": "Play 10 min of LinePlay",
  "short_name": "Queue Navigator"
 },
 {
  "id": 917,
  "slug": "trivia-champ",
  "name": "Trivia Champ",
  "category": "rides",
  "goal": "Win 5 trivia ride challenges",
  "metric": "trivia_wins",
  "target_value": 5,
  "rarity": "rare",
  "image_key": null,
  "emoji": null,
  "is_hidden": false,
  "sort_order": 17,
  "progress": 2,
  "target": 5,
  "progress_percentage": 40,
  "progress_text": "2/5",
  "is_earned": false,
  "earned_at": null,
  "reward_claimed": false,
  "rewards": {
   "energy": 50,
   "tickets": 10,
   "xp": 500,
   "coins": 0,
   "title": "Trivia Champion"
  },
  "section": "rides",
  "icon_url": null,
  "how_to": "Win 5 ride trivia games",
  "short_name": "Trivia Champ"
 },
 {
  "id": 918,
  "slug": "beach-day",
  "name": "Beach Day",
  "category": "friends",
  "goal": "Add 3 friends",
  "metric": "friends_count",
  "target_value": 3,
  "rarity": "common",
  "image_key": null,
  "emoji": null,
  "is_hidden": false,
  "sort_order": 18,
  "progress": 3,
  "target": 3,
  "progress_percentage": 100,
  "progress_text": "3/3",
  "is_earned": true,
  "earned_at": "2026-09-28T12:00:00Z",
  "reward_claimed": false,
  "rewards": {
   "energy": 15,
   "tickets": 2,
   "xp": 100,
   "coins": 0,
   "title": null
  },
  "section": "friends",
  "icon_url": null,
  "how_to": "Add 3 friends",
  "short_name": "Beach Day"
 },
 {
  "id": 919,
  "slug": "social-shark",
  "name": "Social Shark",
  "category": "friends",
  "goal": "Have 10 friends",
  "metric": "friends_count",
  "target_value": 10,
  "rarity": "uncommon",
  "image_key": null,
  "emoji": null,
  "is_hidden": false,
  "sort_order": 19,
  "progress": 10,
  "target": 10,
  "progress_percentage": 100,
  "progress_text": "4/10",
  "is_earned": true,
  "earned_at": "2026-10-05T17:00:00Z",
  "reward_claimed": true,
  "rewards": {
   "energy": 30,
   "tickets": 5,
   "xp": 250,
   "coins": 0,
   "title": null
  },
  "section": "friends",
  "icon_url": null,
  "how_to": "Have 10 friends",
  "short_name": "Social Shark"
 },
 {
  "id": 920,
  "slug": "wave-rider",
  "name": "Wave Rider",
  "category": "streaks",
  "goal": "Catch a find 3 days in a row",
  "metric": "longest_streak",
  "target_value": 3,
  "rarity": "uncommon",
  "image_key": null,
  "emoji": null,
  "is_hidden": false,
  "sort_order": 20,
  "progress": 3,
  "target": 3,
  "progress_percentage": 100,
  "progress_text": "3/3",
  "is_earned": true,
  "earned_at": "2026-09-29T14:00:00Z",
  "reward_claimed": true,
  "rewards": {
   "energy": 25,
   "tickets": 5,
   "xp": 250,
   "coins": 0,
   "title": null
  },
  "section": "streaks",
  "icon_url": null,
  "how_to": "Catch finds 3 days in a row",
  "short_name": "Wave Rider"
 },
 {
  "id": 921,
  "slug": "shark-week",
  "name": "Shark Streak",
  "category": "streaks",
  "goal": "Catch a find 7 days in a row",
  "metric": "longest_streak",
  "target_value": 7,
  "rarity": "rare",
  "image_key": null,
  "emoji": null,
  "is_hidden": false,
  "sort_order": 21,
  "progress": 4,
  "target": 7,
  "progress_percentage": 57,
  "progress_text": "4/7",
  "is_earned": false,
  "earned_at": null,
  "reward_claimed": false,
  "rewards": {
   "energy": 75,
   "tickets": 15,
   "xp": 750,
   "coins": 0,
   "title": null
  },
  "section": "streaks",
  "icon_url": null,
  "how_to": "Catch finds 7 days in a row",
  "short_name": "Shark Streak"
 },
 {
  "id": 922,
  "slug": "week-warrior",
  "name": "Streak Legend",
  "category": "streaks",
  "goal": "Catch a find 14 days in a row",
  "metric": "longest_streak",
  "target_value": 14,
  "rarity": "epic",
  "image_key": null,
  "emoji": null,
  "is_hidden": false,
  "sort_order": 22,
  "progress": 4,
  "target": 14,
  "progress_percentage": 29,
  "progress_text": "4/14",
  "is_earned": false,
  "earned_at": null,
  "reward_claimed": false,
  "rewards": {
   "energy": 50,
   "tickets": 10,
   "xp": 500,
   "coins": 0,
   "title": null
  },
  "section": "streaks",
  "icon_url": null,
  "how_to": "Catch finds 14 days in a row",
  "short_name": "Streak Legend"
 },
 {
  "id": 923,
  "slug": "shark-scholar",
  "name": "Shark Scholar",
  "category": "milestones",
  "goal": "Earn 5,000 XP",
  "metric": "total_experience",
  "target_value": 5000,
  "rarity": "uncommon",
  "image_key": null,
  "emoji": null,
  "is_hidden": false,
  "sort_order": 23,
  "progress": 5000,
  "target": 5000,
  "progress_percentage": 100,
  "progress_text": "5000/5000",
  "is_earned": true,
  "earned_at": "2026-09-30T20:00:00Z",
  "reward_claimed": true,
  "rewards": {
   "energy": 25,
   "tickets": 5,
   "xp": 250,
   "coins": 0,
   "title": null
  },
  "section": "milestones",
  "icon_url": null,
  "how_to": "Earn 5,000 XP",
  "short_name": "Shark Scholar"
 },
 {
  "id": 924,
  "slug": "xp-machine",
  "name": "XP Machine",
  "category": "milestones",
  "goal": "Earn 30,000 XP",
  "metric": "total_experience",
  "target_value": 30000,
  "rarity": "rare",
  "image_key": null,
  "emoji": null,
  "is_hidden": false,
  "sort_order": 24,
  "progress": 8120,
  "target": 30000,
  "progress_percentage": 27,
  "progress_text": "8120/30000",
  "is_earned": false,
  "earned_at": null,
  "reward_claimed": false,
  "rewards": {
   "energy": 75,
   "tickets": 15,
   "xp": 500,
   "coins": 0,
   "title": "XP Machine"
  },
  "section": "milestones",
  "icon_url": null,
  "how_to": "Earn 30,000 XP",
  "short_name": "XP Machine"
 },
 {
  "id": 925,
  "slug": "captain",
  "name": "Captain",
  "category": "milestones",
  "goal": "Save up 2,500 coins",
  "metric": "coins_held",
  "target_value": 2500,
  "rarity": "rare",
  "image_key": null,
  "emoji": null,
  "is_hidden": false,
  "sort_order": 25,
  "progress": 2500,
  "target": 2500,
  "progress_percentage": 100,
  "progress_text": "2500/2500",
  "is_earned": true,
  "earned_at": "2026-10-01T10:00:00Z",
  "reward_claimed": false,
  "rewards": {
   "energy": 50,
   "tickets": 10,
   "xp": 500,
   "coins": 0,
   "title": "Captain"
  },
  "section": "milestones",
  "icon_url": null,
  "how_to": "Save up 2,500 coins",
  "short_name": "Captain"
 },
 {
  "id": 926,
  "slug": "coin-master",
  "name": "Vault Boss",
  "category": "milestones",
  "goal": "Save up 10,000 coins",
  "metric": "coins_held",
  "target_value": 10000,
  "rarity": "epic",
  "image_key": null,
  "emoji": null,
  "is_hidden": false,
  "sort_order": 26,
  "progress": 3100,
  "target": 10000,
  "progress_percentage": 31,
  "progress_text": "3100/10000",
  "is_earned": false,
  "earned_at": null,
  "reward_claimed": false,
  "rewards": {
   "energy": 100,
   "tickets": 25,
   "xp": 1000,
   "coins": 0,
   "title": "Vault Boss"
  },
  "section": "milestones",
  "icon_url": null,
  "how_to": "Save up 10,000 coins",
  "short_name": "Vault Boss"
 },
 {
  "id": 927,
  "slug": "night-owl",
  "name": "Night Owl",
  "category": "special",
  "goal": "Play between midnight and 4 AM",
  "metric": "night_owl",
  "target_value": 1,
  "rarity": "rare",
  "image_key": null,
  "emoji": null,
  "is_hidden": false,
  "sort_order": 27,
  "progress": 1,
  "target": 1,
  "progress_percentage": 100,
  "progress_text": "1/1",
  "is_earned": true,
  "earned_at": "2026-09-28T07:20:00Z",
  "reward_claimed": true,
  "rewards": {
   "energy": 25,
   "tickets": 0,
   "xp": 200,
   "coins": 0,
   "title": null
  },
  "section": "special",
  "icon_url": null,
  "how_to": "Play from 12 to 4 AM",
  "short_name": "Night Owl",
  "retired": true
 },
 {
  "id": 928,
  "slug": "holiday-shark",
  "name": "Holiday Shark",
  "category": "special",
  "goal": "Play on a holiday, like Halloween or New Year's Day",
  "metric": "holiday_login",
  "target_value": 1,
  "rarity": "rare",
  "image_key": null,
  "emoji": null,
  "is_hidden": false,
  "sort_order": 28,
  "progress": 0,
  "target": 1,
  "progress_percentage": 0,
  "progress_text": "0/1",
  "is_earned": false,
  "earned_at": null,
  "reward_claimed": false,
  "rewards": {
   "energy": 50,
   "tickets": 10,
   "xp": 500,
   "coins": 0,
   "title": null
  },
  "section": "special",
  "icon_url": null,
  "how_to": "Play on a holiday",
  "short_name": "Holiday Shark"
 },
 {
  "id": 929,
  "slug": "trail-walker",
  "name": "Trail Walker",
  "category": "steps",
  "goal": "Open your first Trail Box",
  "metric": "trail_boxes_opened",
  "target_value": 1,
  "rarity": "common",
  "image_key": null,
  "emoji": null,
  "is_hidden": false,
  "sort_order": 30,
  "progress": 0,
  "target": 1,
  "progress_percentage": 0,
  "progress_text": "0/1",
  "is_earned": false,
  "earned_at": null,
  "reward_claimed": false,
  "rewards": {
   "energy": 40,
   "tickets": 5,
   "xp": 400,
   "coins": 0,
   "title": null
  },
  "icon_url": null,
  "how_to": "Open your first Trail Box",
  "short_name": "Trail Walker"
 },
 {
  "id": 930,
  "slug": "marathon-shark",
  "name": "Marathon Shark",
  "category": "steps",
  "goal": "Walk 42.2 km in parks",
  "metric": "park_distance_m",
  "target_value": 42200,
  "rarity": "epic",
  "image_key": null,
  "emoji": null,
  "is_hidden": false,
  "sort_order": 30,
  "progress": 12400,
  "target": 42200,
  "progress_percentage": 29,
  "progress_text": "12400/42200",
  "is_earned": false,
  "earned_at": null,
  "reward_claimed": false,
  "rewards": {
   "energy": 40,
   "tickets": 5,
   "xp": 400,
   "coins": 0,
   "title": "Marathon Shark"
  },
  "icon_url": null,
  "how_to": "Walk 42.2 km in parks",
  "short_name": "Marathon Shark"
 }
];

export const PREVIEW_BOOK: StampsResponse = {
  stamps: { book: STAMPS },
  newly_earned: [],
  unlocked_titles: STAMPS.filter(s => s.is_earned && s.reward_claimed && s.rewards.title).map(s => ({ stamp_id: s.id, title: s.rewards.title as string })),
  equipped_title: 'Explorer',
  sections: [...FALLBACK_SECTIONS],
  summary: { total: STAMPS.length, earned: STAMPS.filter(s => s.is_earned).length },
};
