'use strict';
/**
 * Writes src/fx/rigs/kitArt.ts: one static require per sprite kit.json uses (Metro needs literal
 * requires). Run after editing kit.json: node tools/fx/kit-art.cjs. A test checks it is current.
 */
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '../..');
const kit = JSON.parse(fs.readFileSync(path.join(root, 'src/fx/kit.json'), 'utf8'));
const files = new Set();
for (const item of Object.values(kit.items)) {
  for (const p of [...item.parts, ...(item.emitters || [])]) files.add(p.src);
}
const lines = [...files].sort().map(f => `  '${f}': require('../../../assets/fx/${f}'),`);
const out = `// Generated by tools/fx/kit-art.cjs from src/fx/kit.json. Do not edit by hand.\n/* eslint-disable */\nexport const KIT_ART: Record<string, number> = {\n${lines.join('\n')}\n};\n`;
fs.writeFileSync(path.join(root, 'src/fx/rigs/kitArt.ts'), out);
console.log(`kitArt.ts: ${files.size} sprites`);
