/* eslint-disable */
// Generated by tools/whack/import-v4-art.py. Do not edit by hand.
// Whack v4 ship-cut art: gate-passed GPT Image 2.5 subjects made with Alex's references.

import type { WhackThemeId } from './timeline';

type Box = readonly [number, number, number, number, number];

/** v4 costume key poses (8.4), per theme. */
export const KEY_POSES = {
  park: {
    glance: require('../../assets/games/whack/themes/park/glance.png'),
    contact: require('../../assets/games/whack/themes/park/contact.png'),
    bonked_spiral: require('../../assets/games/whack/themes/park/bonked_spiral.png'),
    bonked_tongue: require('../../assets/games/whack/themes/park/bonked_tongue.png'),
    bonked_hatoff: require('../../assets/games/whack/themes/park/bonked_hatoff.png'),
    duck: require('../../assets/games/whack/themes/park/duck.png'),
  },
  pirates: {
    glance: require('../../assets/games/whack/themes/pirates/glance.png'),
    contact: require('../../assets/games/whack/themes/pirates/contact.png'),
    bonked_spiral: require('../../assets/games/whack/themes/pirates/bonked_spiral.png'),
    bonked_tongue: require('../../assets/games/whack/themes/pirates/bonked_tongue.png'),
    bonked_hatoff: require('../../assets/games/whack/themes/pirates/bonked_hatoff.png'),
    duck: require('../../assets/games/whack/themes/pirates/duck.png'),
  },
  mansion: {
    glance: require('../../assets/games/whack/themes/mansion/glance.png'),
    contact: require('../../assets/games/whack/themes/mansion/contact.png'),
    bonked_spiral: require('../../assets/games/whack/themes/mansion/bonked_spiral.png'),
    bonked_tongue: require('../../assets/games/whack/themes/mansion/bonked_tongue.png'),
    bonked_hatoff: require('../../assets/games/whack/themes/mansion/bonked_hatoff.png'),
    duck: require('../../assets/games/whack/themes/mansion/duck.png'),
  },
  space: {
    glance: require('../../assets/games/whack/themes/space/glance.png'),
    contact: require('../../assets/games/whack/themes/space/contact.png'),
    bonked_spiral: require('../../assets/games/whack/themes/space/bonked_spiral.png'),
    bonked_tongue: require('../../assets/games/whack/themes/space/bonked_tongue.png'),
    bonked_hatoff: require('../../assets/games/whack/themes/space/bonked_hatoff.png'),
    duck: require('../../assets/games/whack/themes/space/duck.png'),
  },
  jungle: {
    glance: require('../../assets/games/whack/themes/jungle/glance.png'),
    contact: require('../../assets/games/whack/themes/jungle/contact.png'),
    bonked_spiral: require('../../assets/games/whack/themes/jungle/bonked_spiral.png'),
    bonked_tongue: require('../../assets/games/whack/themes/jungle/bonked_tongue.png'),
    bonked_hatoff: require('../../assets/games/whack/themes/jungle/bonked_hatoff.png'),
    duck: require('../../assets/games/whack/themes/jungle/duck.png'),
  },
  backlot: {
    glance: require('../../assets/games/whack/themes/backlot/glance.png'),
    contact: require('../../assets/games/whack/themes/backlot/contact.png'),
    bonked_spiral: require('../../assets/games/whack/themes/backlot/bonked_spiral.png'),
    bonked_tongue: require('../../assets/games/whack/themes/backlot/bonked_tongue.png'),
    bonked_hatoff: require('../../assets/games/whack/themes/backlot/bonked_hatoff.png'),
    duck: require('../../assets/games/whack/themes/backlot/duck.png'),
  },
} as const;

/** Content boxes [x0, y0, x1, y1, aspect] of the key poses (measured from the @3x files). */
export const KEY_POSE_BOX: Record<WhackThemeId, Record<string, Box>> = {
  park: { glance: [0.134, 0.154, 0.864, 0.963, 1.026], contact: [0.036, 0.383, 0.964, 0.963, 1.026], bonked_spiral: [0.101, 0.084, 0.899, 0.961, 1.026], bonked_tongue: [0.094, 0.095, 0.904, 0.963, 1.026], bonked_hatoff: [0.118, 0.037, 0.882, 0.963, 1.026], duck: [0.139, 0.381, 0.859, 0.963, 1.026] },
  pirates: { glance: [0.103, 0.108, 0.893, 0.96, 1.043], contact: [0.036, 0.389, 0.964, 0.962, 1.043], bonked_spiral: [0.116, 0.1, 0.882, 0.96, 1.043], bonked_tongue: [0.107, 0.087, 0.893, 0.96, 1.043], bonked_hatoff: [0.094, 0.038, 0.906, 0.96, 1.043], duck: [0.101, 0.378, 0.895, 0.96, 1.043] },
  mansion: { glance: [0.119, 0.112, 0.877, 0.961, 1.033], contact: [0.035, 0.202, 0.965, 0.963, 1.033], bonked_spiral: [0.078, 0.127, 0.92, 0.961, 1.033], bonked_tongue: [0.088, 0.106, 0.91, 0.963, 1.033], bonked_hatoff: [0.106, 0.037, 0.892, 0.961, 1.033], duck: [0.08, 0.285, 0.918, 0.963, 1.033] },
  space: { glance: [0.166, 0.063, 0.832, 0.964, 1.019], contact: [0.037, 0.336, 0.965, 0.964, 1.019], bonked_spiral: [0.132, 0.055, 0.87, 0.962, 1.019], bonked_tongue: [0.119, 0.078, 0.879, 0.962, 1.019], bonked_hatoff: [0.242, 0.042, 0.758, 0.96, 1.019], duck: [0.153, 0.275, 0.847, 0.964, 1.019] },
  jungle: { glance: [0.17, 0.103, 0.83, 0.959, 1.068], contact: [0.036, 0.18, 0.964, 0.961, 1.068], bonked_spiral: [0.125, 0.11, 0.873, 0.959, 1.068], bonked_tongue: [0.107, 0.081, 0.889, 0.959, 1.068], bonked_hatoff: [0.15, 0.039, 0.851, 0.959, 1.068], duck: [0.13, 0.34, 0.87, 0.959, 1.068] },
  backlot: { glance: [0.121, 0.113, 0.877, 0.962, 0.983], contact: [0.037, 0.489, 0.961, 0.962, 0.983], bonked_spiral: [0.099, 0.036, 0.899, 0.964, 0.983], bonked_tongue: [0.138, 0.055, 0.862, 0.964, 0.983], bonked_hatoff: [0.111, 0.05, 0.885, 0.962, 0.983], duck: [0.097, 0.424, 0.899, 0.964, 0.983] },
};

export const HATS: Record<WhackThemeId, number> = {
  park: require('../../assets/games/whack/themes/park/hat.png'),
  pirates: require('../../assets/games/whack/themes/pirates/hat.png'),
  mansion: require('../../assets/games/whack/themes/mansion/hat.png'),
  space: require('../../assets/games/whack/themes/space/hat.png'),
  jungle: require('../../assets/games/whack/themes/jungle/hat.png'),
  backlot: require('../../assets/games/whack/themes/backlot/hat.png'),
};
export const HAT_BOX: Record<WhackThemeId, Box> = {
  park: [0.038, 0.057, 0.965, 0.948, 1.485],
  pirates: [0.038, 0.06, 0.965, 0.94, 1.574],
  mansion: [0.04, 0.038, 0.96, 0.962, 0.962],
  space: [0.035, 0.038, 0.962, 0.958, 1.108],
  jungle: [0.038, 0.053, 0.962, 0.947, 1.391],
  backlot: [0.038, 0.057, 0.965, 0.948, 1.492],
};

export const DECKS: Record<WhackThemeId, number> = {
  park: require('../../assets/games/whack/decks/park.jpg'),
  pirates: require('../../assets/games/whack/decks/pirates.jpg'),
  mansion: require('../../assets/games/whack/decks/mansion.jpg'),
  space: require('../../assets/games/whack/decks/space.jpg'),
  jungle: require('../../assets/games/whack/decks/jungle.jpg'),
  backlot: require('../../assets/games/whack/decks/backlot.jpg'),
};

export const RIM_WARNING = { teeth: require('../../assets/games/whack/rims/warning_teeth.png'), tab: require('../../assets/games/whack/rims/warning_tab.png') };
export const RIM_WARNING_BOX = { teeth: [0.038, 0.056, 0.962, 0.944, 1.609] as Box, tab: [0.044, 0.035, 0.956, 0.965, 0.788] as Box };
export const SPEEDLINES = require('../../assets/games/whack/fx/speedlines.png');

export const PROPS = {
  pirates_bow: require('../../assets/games/whack/props/pirates_bow.png'),
  mansion_gate: require('../../assets/games/whack/props/mansion_gate.png'),
  space_gantry: require('../../assets/games/whack/props/space_gantry.png'),
  jungle_steps: require('../../assets/games/whack/props/jungle_steps.png'),
  backlot_light_a: require('../../assets/games/whack/props/backlot_light_a.png'),
  backlot_light_b: require('../../assets/games/whack/props/backlot_light_b.png'),
  backlot_chair: require('../../assets/games/whack/props/backlot_chair.png'),
};
export const PROP_BOX: Record<keyof typeof PROPS, Box> = {
  pirates_bow: [0.045, 0.039, 0.955, 0.964, 0.867],
  mansion_gate: [0.036, 0.048, 0.964, 0.952, 1.315],
  space_gantry: [0.045, 0.036, 0.955, 0.964, 0.805],
  jungle_steps: [0.036, 0.058, 0.964, 0.942, 1.6],
  backlot_light_a: [0.063, 0.036, 0.937, 0.964, 0.578],
  backlot_light_b: [0.064, 0.036, 0.936, 0.964, 0.57],
  backlot_chair: [0.044, 0.036, 0.959, 0.964, 0.823],
};
