#!/usr/bin/env python3
"""Regenerate src/share/placeNames.ts from the backend's ride seeds.

usage: build-place-names.py <backend checkout>
Ride and task names come from database/seeders/RideSeeder.php and
database/seeders/data/tasks.json. Parks, resorts and IP franchises are listed
here. Generic words (Bridge, Castle, Games...) are skipped so catalog names
like "Sand Castle" survive; anything ride-specific is kept.
"""
import json, re, sys, pathlib

be = pathlib.Path(sys.argv[1])
names = set()
src = (be / 'database/seeders/RideSeeder.php').read_text()
for m in re.finditer(r"'name' => (?:'((?:[^'\\]|\\.)*)'|\"([^\"]*)\")", src):
    names.add((m.group(1) or m.group(2)).replace("\\'", "'"))
for t in json.loads((be / 'database/seeders/data/tasks.json').read_text()):
    names.add(t['name'])

GENERIC = {
    'Bridge', 'Castle', 'Games', 'Cars', 'Spider', 'Snowball', 'Lighthouse', 'Midway', 'The Arch', 'The Globe',
    'The Theatre', 'Red Button', 'Shark Statue', 'StorePants', 'Walt Statue', 'Sky School', 'Secret Alley',
    'Fire Department', 'Discovery Center', 'Courthouse Square', 'Supercharged', 'Pirates', 'World of Water',
    'Hollywood Star', 'Universal Plaza', 'Smugglers', 'Mummy', 'Studio Tour', 'Cafe 4', 'Butter Drink',
    'Picture Perfect Waterfall', 'Award Wieners', 'Simpson Game', 'River Adventure', 'Thunder Falls Terrace',
    'Port Of Entry', 'Sonoma Terrace', 'Jurassic Entrance', 'Pixar Pier Entrance', 'Mario World', 'Super Silly',
    'Inside Out', 'Golden Zephyr', 'Mr. Lincoln', "Mel's", 'Pal-A-Round', 'Animal Actors',
}
PLACES = [
    # parks and resorts
    'Walt Disney World', 'Disney World', 'Disneyland Resort', 'Disneyland Park', 'Disneyland', 'Magic Kingdom', 'EPCOT',
    'Hollywood Studios', 'Animal Kingdom', 'California Adventure', 'Disney California Adventure',
    'Universal Studios Hollywood', 'Universal Studios Florida', 'Universal Studios', 'Universal Orlando',
    'Universal Hollywood', 'Universal', 'Epic Universe', 'Islands of Adventure', 'Volcano Bay', 'CityWalk',
    'Downtown Disney', 'Disney Springs', 'SeaWorld', 'Busch Gardens', 'Six Flags', "Knott's Berry Farm",
    'Legoland', 'Cedar Point', 'Disney', 'Orlando', 'Anaheim',
    # franchises and lands that pin a park
    'Harry Potter', 'Hogwarts', 'Diagon Alley', 'Star Wars', "Galaxy's Edge", 'Marvel', 'Avengers Campus',
    'Super Nintendo World', 'Nintendo', 'Pixar', 'Mickey', 'Minnie', 'Minion', 'Minions', 'Toy Story',
    'Jurassic Park', 'Jurassic World', 'Fantasyland', 'Tomorrowland', 'Frontierland', 'Adventureland',
    'Halloween Horror Nights', 'Horror Nights', 'HHN',
]
rides = sorted({n.strip() for n in names if n.strip() and n.strip() not in GENERIC and len(n.strip()) >= 4})
all_names = sorted(set(PLACES) | set(rides), key=lambda s: (-len(s), s.lower()))

out = pathlib.Path(__file__).resolve().parents[2] / 'src/share/placeNames.ts'
body = ',\n'.join(f'  {json.dumps(n)}' for n in all_names)
out.write_text(f'''/**
 * Park, resort, land, franchise and ride names that must never print on a flex
 * card (CONTRACT.md section 4). Generated by tools/share-studio/build-place-names.py
 * from the backend ride seeds; longest first so "Revenge of the Mummy" goes
 * before any shorter overlap. Do not edit by hand.
 */
export const PLACE_NAMES: readonly string[] = [
{body},
];
''')
print(f'{len(all_names)} names -> {out}')
