#!/usr/bin/env python3
"""
Import the Whack v4 ship-cut art (art lead output, gate-passed, GPT Image 2.5
with Alex's references) into the app and write src/games/whack/art.generated.ts
with literal requires and measured content boxes.

    python3 tools/whack/import-v4-art.py

Source: /Users/dustinsparage/apps/tps-mg/art/whack (manifest.json, wave 6).
Decks become opaque JPEGs (they are floors, no alpha); everything else stays PNG
at @1x/@2x/@3x. Nothing is restyled: files are copied or resized only.
"""
import json, os, shutil
from PIL import Image

SRC = '/Users/dustinsparage/apps/tps-mg/art/whack'
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '../..'))
DST = os.path.join(ROOT, 'src/assets/games/whack')
THEMES = ['park', 'pirates', 'mansion', 'space', 'jungle', 'backlot']
POSES = ['glance', 'contact', 'bonked_spiral', 'bonked_tongue', 'bonked_hatoff', 'duck']

def box(path):
    im = Image.open(path).convert('RGBA')
    a = im.split()[3].point(lambda v: 255 if v > 24 else 0)
    x0, y0, x1, y1 = a.getbbox()
    w, h = im.size
    return [round(x0 / w, 3), round(y0 / h, 3), round(x1 / w, 3), round(y1 / h, 3), round(w / h, 3)]

def copy_set(src_base, dst_base):
    """src_base without extension; copies base, @2x, @3x (base = the @1x file when present)."""
    os.makedirs(os.path.dirname(dst_base), exist_ok=True)
    one = src_base + '@1x.png'
    shutil.copyfile(one if os.path.exists(one) else src_base + '.png', dst_base + '.png')
    for s in ('@2x', '@3x'):
        if os.path.exists(src_base + s + '.png'):
            shutil.copyfile(src_base + s + '.png', dst_base + s + '.png')
    return box(src_base + ('@3x.png' if os.path.exists(src_base + '@3x.png') else '.png'))

lines = ['/* eslint-disable */', '// Generated by tools/whack/import-v4-art.py. Do not edit by hand.', '// Whack v4 ship-cut art: gate-passed GPT Image 2.5 subjects made with Alex\'s references.', '',
         "import type { WhackThemeId } from './timeline';", '', 'type Box = readonly [number, number, number, number, number];', '']

poses = {}
for t in THEMES:
    poses[t] = {}
    for p in POSES:
        poses[t][p] = copy_set(f'{SRC}/themes/{t}/wh_{t}_{p}', f'{DST}/themes/{t}/{p}')
hats = {t: copy_set(f'{SRC}/hats/wh_hat_{t}', f'{DST}/themes/{t}/hat') for t in THEMES}
teeth = copy_set(f'{SRC}/rims/wh_rim_warning_teeth', f'{DST}/rims/warning_teeth')
tab = copy_set(f'{SRC}/rims/wh_rim_warning_tab', f'{DST}/rims/warning_tab')
speed = copy_set(f'{SRC}/fx/wh_speedlines', f'{DST}/fx/speedlines')
props = {}
for name in ['pirates_bow', 'mansion_gate', 'space_gantry', 'jungle_steps', 'backlot_light_a', 'backlot_light_b', 'backlot_chair']:
    props[name] = copy_set(f'{SRC}/props/wh_prop_{name}', f'{DST}/props/{name}')
os.makedirs(f'{DST}/decks', exist_ok=True)
for t in THEMES:
    im = Image.open(f'{SRC}/decks/deck_{t}.png').convert('RGB')
    im.resize((1152, 768), Image.LANCZOS).save(f'{DST}/decks/{t}.jpg', quality=84, optimize=True)

lines.append('/** v4 costume key poses (8.4), per theme. */')
lines.append('export const KEY_POSES = {')
for t in THEMES:
    lines.append(f'  {t}: {{')
    for p in POSES:
        lines.append(f"    {p}: require('../../assets/games/whack/themes/{t}/{p}.png'),")
    lines.append('  },')
lines.append('} as const;')
lines.append('')
lines.append('/** Content boxes [x0, y0, x1, y1, aspect] of the key poses (measured from the @3x files). */')
lines.append('export const KEY_POSE_BOX: Record<WhackThemeId, Record<string, Box>> = {')
for t in THEMES:
    lines.append(f'  {t}: {{ ' + ', '.join(f'{p}: {json.dumps(poses[t][p])}' for p in POSES) + ' },')
lines.append('};')
lines.append('')
lines.append('export const HATS: Record<WhackThemeId, number> = {')
for t in THEMES:
    lines.append(f"  {t}: require('../../assets/games/whack/themes/{t}/hat.png'),")
lines.append('};')
lines.append('export const HAT_BOX: Record<WhackThemeId, Box> = {')
for t in THEMES:
    lines.append(f'  {t}: {json.dumps(hats[t])},')
lines.append('};')
lines.append('')
lines.append('export const DECKS: Record<WhackThemeId, number> = {')
for t in THEMES:
    lines.append(f"  {t}: require('../../assets/games/whack/decks/{t}.jpg'),")
lines.append('};')
lines.append('')
lines.append("export const RIM_WARNING = { teeth: require('../../assets/games/whack/rims/warning_teeth.png'), tab: require('../../assets/games/whack/rims/warning_tab.png') };")
lines.append(f'export const RIM_WARNING_BOX = {{ teeth: {json.dumps(teeth)} as Box, tab: {json.dumps(tab)} as Box }};')
lines.append("export const SPEEDLINES = require('../../assets/games/whack/fx/speedlines.png');")
lines.append('')
lines.append('export const PROPS = {')
for k in props:
    lines.append(f"  {k}: require('../../assets/games/whack/props/{k}.png'),")
lines.append('};')
lines.append('export const PROP_BOX: Record<keyof typeof PROPS, Box> = {')
for k, v in props.items():
    lines.append(f'  {k}: {json.dumps(v)},')
lines.append('};')
lines.append('')
open(os.path.join(ROOT, 'src/games/whack/art.generated.ts'), 'w').write('\n'.join(lines))
print('ok', sum(os.path.getsize(os.path.join(dp, f)) for dp, _, fs in os.walk(DST) for f in fs) // 1024, 'KB under', DST)
