/* eslint-disable */
// Baked Current Quest sequences (audio lead; carries on the v7.1 J6 curve: grab 80 ms,
// ticks at 110/90/75/65 ms per tile, spit-out at 80 + T(n) + 40 ms). Dev-only candidates:
// required only under __DEV__ until Dustin approves them by ear.
import type { CueDef } from '../../gamekit/audio/chrisBank';

export const CQ_SEQ_CUES: Record<string, CueDef> = {
  'cq_carry_1': { src: require('../../assets/games/current-quest/seq/cq_carry_1.m4a'), durationMs: 750, bus: 'sfx', maxVoices: 2, priority: 2, approved: false },
  'cq_carry_1_rip': { src: require('../../assets/games/current-quest/seq/cq_carry_1_rip.m4a'), durationMs: 750, bus: 'sfx', maxVoices: 2, priority: 2, approved: false },
  'cq_carry_2': { src: require('../../assets/games/current-quest/seq/cq_carry_2.m4a'), durationMs: 840, bus: 'sfx', maxVoices: 2, priority: 2, approved: false },
  'cq_carry_2_rip': { src: require('../../assets/games/current-quest/seq/cq_carry_2_rip.m4a'), durationMs: 840, bus: 'sfx', maxVoices: 2, priority: 2, approved: false },
  'cq_carry_3': { src: require('../../assets/games/current-quest/seq/cq_carry_3.m4a'), durationMs: 915, bus: 'sfx', maxVoices: 2, priority: 2, approved: false },
  'cq_carry_3_rip': { src: require('../../assets/games/current-quest/seq/cq_carry_3_rip.m4a'), durationMs: 915, bus: 'sfx', maxVoices: 2, priority: 2, approved: false },
  'cq_carry_4': { src: require('../../assets/games/current-quest/seq/cq_carry_4.m4a'), durationMs: 980, bus: 'sfx', maxVoices: 2, priority: 2, approved: false },
  'cq_carry_4_rip': { src: require('../../assets/games/current-quest/seq/cq_carry_4_rip.m4a'), durationMs: 980, bus: 'sfx', maxVoices: 2, priority: 2, approved: false },
  'cq_carry_5': { src: require('../../assets/games/current-quest/seq/cq_carry_5.m4a'), durationMs: 1045, bus: 'sfx', maxVoices: 2, priority: 2, approved: false },
  'cq_carry_5_rip': { src: require('../../assets/games/current-quest/seq/cq_carry_5_rip.m4a'), durationMs: 1045, bus: 'sfx', maxVoices: 2, priority: 2, approved: false },
  'cq_carry_6': { src: require('../../assets/games/current-quest/seq/cq_carry_6.m4a'), durationMs: 1110, bus: 'sfx', maxVoices: 2, priority: 2, approved: false },
  'cq_carry_6_rip': { src: require('../../assets/games/current-quest/seq/cq_carry_6_rip.m4a'), durationMs: 1110, bus: 'sfx', maxVoices: 2, priority: 2, approved: false },
  'cq_carry_7': { src: require('../../assets/games/current-quest/seq/cq_carry_7.m4a'), durationMs: 1175, bus: 'sfx', maxVoices: 2, priority: 2, approved: false },
  'cq_carry_7_rip': { src: require('../../assets/games/current-quest/seq/cq_carry_7_rip.m4a'), durationMs: 1175, bus: 'sfx', maxVoices: 2, priority: 2, approved: false },
  'cq_carry_8': { src: require('../../assets/games/current-quest/seq/cq_carry_8.m4a'), durationMs: 1240, bus: 'sfx', maxVoices: 2, priority: 2, approved: false },
  'cq_carry_8_rip': { src: require('../../assets/games/current-quest/seq/cq_carry_8_rip.m4a'), durationMs: 1240, bus: 'sfx', maxVoices: 2, priority: 2, approved: false },
  'cq_carry_9': { src: require('../../assets/games/current-quest/seq/cq_carry_9.m4a'), durationMs: 1305, bus: 'sfx', maxVoices: 2, priority: 2, approved: false },
  'cq_carry_9_rip': { src: require('../../assets/games/current-quest/seq/cq_carry_9_rip.m4a'), durationMs: 1305, bus: 'sfx', maxVoices: 2, priority: 2, approved: false },
  'cq_carry_10': { src: require('../../assets/games/current-quest/seq/cq_carry_10.m4a'), durationMs: 1370, bus: 'sfx', maxVoices: 2, priority: 2, approved: false },
  'cq_carry_10_rip': { src: require('../../assets/games/current-quest/seq/cq_carry_10_rip.m4a'), durationMs: 1370, bus: 'sfx', maxVoices: 2, priority: 2, approved: false },
  'cq_leftover_1': { src: require('../../assets/games/current-quest/seq/cq_leftover_1.wav'), durationMs: 430, bus: 'sfx', maxVoices: 2, priority: 2, approved: false },
  'cq_leftover_2': { src: require('../../assets/games/current-quest/seq/cq_leftover_2.wav'), durationMs: 505, bus: 'sfx', maxVoices: 2, priority: 2, approved: false },
  'cq_leftover_3': { src: require('../../assets/games/current-quest/seq/cq_leftover_3.wav'), durationMs: 580, bus: 'sfx', maxVoices: 2, priority: 2, approved: false },
  'cq_leftover_4': { src: require('../../assets/games/current-quest/seq/cq_leftover_4.wav'), durationMs: 655, bus: 'sfx', maxVoices: 2, priority: 2, approved: false },
  'cq_leftover_5': { src: require('../../assets/games/current-quest/seq/cq_leftover_5.wav'), durationMs: 730, bus: 'sfx', maxVoices: 2, priority: 2, approved: false },
  'cq_leftover_6': { src: require('../../assets/games/current-quest/seq/cq_leftover_6.wav'), durationMs: 805, bus: 'sfx', maxVoices: 2, priority: 2, approved: false },
  'cq_leftover_7': { src: require('../../assets/games/current-quest/seq/cq_leftover_7.wav'), durationMs: 880, bus: 'sfx', maxVoices: 2, priority: 2, approved: false },
  'cq_leftover_8': { src: require('../../assets/games/current-quest/seq/cq_leftover_8.wav'), durationMs: 955, bus: 'sfx', maxVoices: 2, priority: 2, approved: false },
  'cq_leftover_9': { src: require('../../assets/games/current-quest/seq/cq_leftover_9.wav'), durationMs: 1030, bus: 'sfx', maxVoices: 2, priority: 2, approved: false },
  'cq_leftover_10': { src: require('../../assets/games/current-quest/seq/cq_leftover_10.wav'), durationMs: 1105, bus: 'sfx', maxVoices: 2, priority: 2, approved: false },
  'cq_shells_1': { src: require('../../assets/games/current-quest/seq/cq_shells_1.wav'), durationMs: 267, bus: 'sfx', maxVoices: 2, priority: 2, approved: false },
  'cq_shells_2': { src: require('../../assets/games/current-quest/seq/cq_shells_2.wav'), durationMs: 377, bus: 'sfx', maxVoices: 2, priority: 2, approved: false },
  'cq_shells_3': { src: require('../../assets/games/current-quest/seq/cq_shells_3.wav'), durationMs: 487, bus: 'sfx', maxVoices: 2, priority: 2, approved: false },
  'cq_tally_1': { src: require('../../assets/games/current-quest/seq/cq_tally_1.wav'), durationMs: 450, bus: 'sfx', maxVoices: 2, priority: 2, approved: false },
  'cq_tally_2': { src: require('../../assets/games/current-quest/seq/cq_tally_2.wav'), durationMs: 525, bus: 'sfx', maxVoices: 2, priority: 2, approved: false },
  'cq_tally_3': { src: require('../../assets/games/current-quest/seq/cq_tally_3.wav'), durationMs: 600, bus: 'sfx', maxVoices: 2, priority: 2, approved: false },
  'cq_tally_4': { src: require('../../assets/games/current-quest/seq/cq_tally_4.wav'), durationMs: 675, bus: 'sfx', maxVoices: 2, priority: 2, approved: false },
  'cq_tally_5': { src: require('../../assets/games/current-quest/seq/cq_tally_5.wav'), durationMs: 750, bus: 'sfx', maxVoices: 2, priority: 2, approved: false },
  'cq_tally_6': { src: require('../../assets/games/current-quest/seq/cq_tally_6.wav'), durationMs: 825, bus: 'sfx', maxVoices: 2, priority: 2, approved: false },
  'cq_tally_7': { src: require('../../assets/games/current-quest/seq/cq_tally_7.wav'), durationMs: 900, bus: 'sfx', maxVoices: 2, priority: 2, approved: false },
  'cq_tally_8': { src: require('../../assets/games/current-quest/seq/cq_tally_8.wav'), durationMs: 975, bus: 'sfx', maxVoices: 2, priority: 2, approved: false },
  'cq_tally_9': { src: require('../../assets/games/current-quest/seq/cq_tally_9.wav'), durationMs: 1050, bus: 'sfx', maxVoices: 2, priority: 2, approved: false },
};
