#!/usr/bin/env node
'use strict';
/**
 * Banana Basket: bake the integer tables the deterministic sim uses.
 *
 * Floats and sqrt are allowed HERE (build time) and nowhere in the sim. The
 * output (src/games/banana-basket/tables.ts) is pure integers, so the TS sim,
 * the tests and the server replay port (BananaReplay.php, WS7) read the exact
 * same numbers.
 *
 *   node tools/banana/gen-tables.cjs          # write tables.ts
 *   node tools/banana/gen-tables.cjs --check  # exit 1 if tables.ts is stale
 */
const fs = require('node:fs');
const path = require('node:path');

const OUT = path.resolve(__dirname, '../../src/games/banana-basket/tables.ts');

const SUB = 256; // sub-units per field unit
const HZ = 60;
const perStep = (fuPerSec) => Math.round((fuPerSec * SUB) / HZ);
const perStep2 = (fuPerSec2) => Math.round((fuPerSec2 * SUB) / (HZ * HZ));

// Thumb-driven time ramps (q8, 256 = 1.0). Ease-out up over 12 steps, ease-in down over 8.
const RAMP_UP = [];
for (let i = 1; i <= 12; i++) {
  const t = i / 12;
  RAMP_UP.push(Math.round(256 * (1 - (1 - t) * (1 - t) * (1 - t))));
}
const RAMP_DOWN = [];
for (let i = 1; i <= 8; i++) {
  const t = i / 8;
  RAMP_DOWN.push(Math.round(256 * (1 - t * t)));
}

// Basket movement (rev 8, must match sim.ts moveBasket): within SNAP (80 fu)
// the basket lands on the target this step (1:1), else it sweeps 40 fu/step.
const SNAP = 80;
const SWEEP = 40;
const TRAVEL_MAX = 320;
const TRAVEL = [];
for (let dx = 0; dx <= TRAVEL_MAX; dx++) TRAVEL.push(dx === 0 ? 0 : dx <= SNAP ? 1 : 1 + Math.ceil((dx - SNAP) / SWEEP));

// Inverse of TRAVEL: the farthest dx (fu) the basket covers from rest in n steps.
const MAXDX = [];
for (let n = 0; n <= 120; n++) {
  let best = 0;
  for (let dx = 0; dx <= TRAVEL_MAX; dx++) if (TRAVEL[dx] <= n) best = dx;
  MAXDX.push(best);
}

// Juggle ball: bounce n keeps the apex at 302 fu while the cycle gets faster.
const APEX = 302;
const G_BALL = [];
const VY_BALL = [];
// Low Gravity twist: gravity x0.8 with the apex unchanged (vy scales by sqrt 0.8).
const G_BALL_LO = [];
const VY_BALL_LO = [];
for (let n = 0; n <= 12; n++) {
  const g = 900 + 25 * n;
  G_BALL.push(perStep2(g));
  VY_BALL.push(-perStep(Math.sqrt(2 * g * APEX)));
  G_BALL_LO.push(perStep2(g * 0.8));
  VY_BALL_LO.push(-perStep(Math.sqrt(2 * g * 0.8 * APEX)));
}

const tables = { RAMP_UP, RAMP_DOWN, TRAVEL, MAXDX, G_BALL, VY_BALL, G_BALL_LO, VY_BALL_LO };
const lines = [
  '/**',
  ' * GENERATED by tools/banana/gen-tables.cjs. Do not edit by hand.',
  ' * Integer tables for the deterministic Banana Basket sim (sub-units of',
  ' * 1/256 field unit, steps of 1/60 s, timescales q8). Shared with the',
  ' * server replay port through studio/handoff/banana/constants.json.',
  ' */',
  '',
];
for (const [k, v] of Object.entries(tables)) {
  lines.push(`export const ${k}: readonly number[] = [${v.join(', ')}];`);
}
lines.push('');
lines.push(`export const TRAVEL_MAX = ${TRAVEL_MAX};`);
lines.push('');
const text = lines.join('\n');

if (process.argv.includes('--check')) {
  const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (cur !== text) {
    console.error('tables.ts is stale: run node tools/banana/gen-tables.cjs');
    process.exit(1);
  }
  console.log('tables.ts up to date');
} else {
  fs.writeFileSync(OUT, text);
  console.log(`wrote ${path.relative(process.cwd(), OUT)} (TRAVEL[276]=${TRAVEL[276]} steps)`);
}
module.exports = { tables };
