#!/usr/bin/env node
/**
 * Writes src/games/rhythm/stages/simStages.generated.ts: the ride-format stage
 * data (beat map + canonical sprint chart) of the Line Party sprint stages as
 * a plain TS module, so the party sim bundle (tools/build-sim-bundle.mjs,
 * TS-only, no JSON imports) carries the exact charts the phones play.
 *
 *   node tools/rhythm/export_sim_stages.mjs
 *
 * Re-run after tools/rhythm/author_charts.py; tests fail if it is stale.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const IDS = ['opening_day_a', 'waiting_room_a'];

export function simStagesSource() {
  const out = {};
  for (const id of IDS) {
    const st = JSON.parse(fs.readFileSync(path.join(root, `src/games/rhythm/stages/${id}.json`), 'utf8'));
    out[id] = { id: st.id, title: st.title, key: st.key, bpm: st.bpm, chartVersion: st.chartVersion, formats: { ride: st.formats.ride } };
  }
  return `/* eslint-disable */\n// Generated by tools/rhythm/export_sim_stages.mjs from the stage JSON. Do not edit.\n// The Line Party sim bundle is TS-only, so the sprint charts ship as a module.\n\nexport const SIM_STAGES: Record<string, unknown> = ${JSON.stringify(out)};\n`;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  const file = path.join(root, 'src/games/rhythm/stages/simStages.generated.ts');
  fs.writeFileSync(file, simStagesSource());
  console.log('wrote', path.relative(root, file), fs.statSync(file).size, 'bytes');
}
