/**
 * Generated by tools/build-sim-bundle.mjs --app. Do not edit.
 * The content hash of the party sim bundle this build plays: sent at join and
 * on every submit so the server can match it to the replay bundle (design 11.2).
 */
export const SIM_BUNDLE = 'eb4d5074ce4b';
