/**
 * Dev-only collection book preview data for the five live prep-item sets
 * (names and rarities from the backend seeders), so the preview shows the
 * bundled art by variant slug. Loaded only by SetCollectionPreviewScreen when
 * EXPO_PUBLIC_DEX_PREVIEW_LEGACY=1 (never ships).
 * Generated by tools/assets/prep_items/subjects.py.
 */
import type { MockDexSet } from './mockDexCatalog';

export const MOCK_LEGACY_PREP_SETS: readonly MockDexSet[] = [
 {
  "slug": "churro_collection",
  "name": "Churro Collection",
  "color": "#B5562E",
  "reward": {
   "energy": 200,
   "tickets": 50,
   "xp": 1000,
   "title": "Churro Connoisseur"
  },
  "spawn": "always",
  "badge": "churro_40",
  "items": [
   {
    "slug": "churro_01",
    "name": "Classic Cinnamon",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "churro_01"
   },
   {
    "slug": "churro_02",
    "name": "Sugar Dusted",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "churro_02"
   },
   {
    "slug": "churro_03",
    "name": "Honey Glazed",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "churro_03"
   },
   {
    "slug": "churro_04",
    "name": "Brown Sugar",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "churro_04"
   },
   {
    "slug": "churro_05",
    "name": "Maple Swirl",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "churro_05"
   },
   {
    "slug": "churro_06",
    "name": "Vanilla Bean",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "churro_06"
   },
   {
    "slug": "churro_07",
    "name": "Caramel Drizzle",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "churro_07"
   },
   {
    "slug": "churro_08",
    "name": "Dulce de Leche",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "churro_08"
   },
   {
    "slug": "churro_09",
    "name": "Butterscotch",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "churro_09"
   },
   {
    "slug": "churro_10",
    "name": "Toasted Coconut",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "churro_10"
   },
   {
    "slug": "churro_11",
    "name": "Churro Original",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "churro_11"
   },
   {
    "slug": "churro_12",
    "name": "Cinnamon Toast",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "churro_12"
   },
   {
    "slug": "churro_13",
    "name": "Golden Crisp",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "churro_13"
   },
   {
    "slug": "churro_14",
    "name": "Sweet Cream",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "churro_14"
   },
   {
    "slug": "churro_15",
    "name": "Salted Caramel",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "churro_15"
   },
   {
    "slug": "churro_16",
    "name": "Toffee Crunch",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "churro_16"
   },
   {
    "slug": "churro_17",
    "name": "Praline",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "churro_17"
   },
   {
    "slug": "churro_18",
    "name": "Snickerdoodle",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "churro_18"
   },
   {
    "slug": "churro_19",
    "name": "Biscoff",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "churro_19"
   },
   {
    "slug": "churro_20",
    "name": "Cookie Butter",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "churro_20"
   },
   {
    "slug": "churro_21",
    "name": "Chocolate Dipped",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "churro_21"
   },
   {
    "slug": "churro_22",
    "name": "Strawberry Frosted",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "churro_22"
   },
   {
    "slug": "churro_23",
    "name": "Blueberry Bliss",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "churro_23"
   },
   {
    "slug": "churro_24",
    "name": "Matcha Green Tea",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "churro_24"
   },
   {
    "slug": "churro_25",
    "name": "Ube Purple Yam",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "churro_25"
   },
   {
    "slug": "churro_26",
    "name": "Red Velvet",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "churro_26"
   },
   {
    "slug": "churro_27",
    "name": "Orange Creamsicle",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "churro_27"
   },
   {
    "slug": "churro_28",
    "name": "Lemon Zest",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "churro_28"
   },
   {
    "slug": "churro_29",
    "name": "Mint Chocolate",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "churro_29"
   },
   {
    "slug": "churro_30",
    "name": "Cookies & Cream",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "churro_30"
   },
   {
    "slug": "churro_31",
    "name": "Pumpkin Spice",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "churro_31"
   },
   {
    "slug": "churro_32",
    "name": "Birthday Cake",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "churro_32"
   },
   {
    "slug": "churro_33",
    "name": "Cotton Candy",
    "rarity": 3,
    "flavor": "",
    "variantSlug": "churro_33"
   },
   {
    "slug": "churro_34",
    "name": "Tropical Mango",
    "rarity": 3,
    "flavor": "",
    "variantSlug": "churro_34"
   },
   {
    "slug": "churro_35",
    "name": "Galaxy Swirl",
    "rarity": 3,
    "flavor": "",
    "variantSlug": "churro_35"
   },
   {
    "slug": "churro_36",
    "name": "Electric Blue",
    "rarity": 3,
    "flavor": "",
    "variantSlug": "churro_36"
   },
   {
    "slug": "churro_37",
    "name": "Watermelon Wave",
    "rarity": 3,
    "flavor": "",
    "variantSlug": "churro_37"
   },
   {
    "slug": "churro_38",
    "name": "Sunset Orange",
    "rarity": 3,
    "flavor": "",
    "variantSlug": "churro_38"
   },
   {
    "slug": "churro_39",
    "name": "Golden Churro",
    "rarity": 5,
    "flavor": "",
    "variantSlug": "churro_39"
   },
   {
    "slug": "churro_40",
    "name": "Rainbow Galaxy",
    "rarity": 5,
    "flavor": "",
    "variantSlug": "churro_40"
   }
  ]
 },
 {
  "slug": "pretzel_collection",
  "name": "Pretzel Collection",
  "color": "#C98A3A",
  "reward": {
   "energy": 200,
   "tickets": 50,
   "xp": 1000,
   "title": "Pretzel Master"
  },
  "spawn": "always",
  "badge": "pretzel_40",
  "items": [
   {
    "slug": "pretzel_01",
    "name": "Classic Salted",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "pretzel_01"
   },
   {
    "slug": "pretzel_02",
    "name": "Butter Brushed",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "pretzel_02"
   },
   {
    "slug": "pretzel_03",
    "name": "Garlic Parmesan",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "pretzel_03"
   },
   {
    "slug": "pretzel_04",
    "name": "Sesame Seed",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "pretzel_04"
   },
   {
    "slug": "pretzel_05",
    "name": "Everything Seasoned",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "pretzel_05"
   },
   {
    "slug": "pretzel_06",
    "name": "Poppy Seed",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "pretzel_06"
   },
   {
    "slug": "pretzel_07",
    "name": "Sea Salt",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "pretzel_07"
   },
   {
    "slug": "pretzel_08",
    "name": "Herb Butter",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "pretzel_08"
   },
   {
    "slug": "pretzel_09",
    "name": "Onion Flake",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "pretzel_09"
   },
   {
    "slug": "pretzel_10",
    "name": "Rosemary",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "pretzel_10"
   },
   {
    "slug": "pretzel_11",
    "name": "Plain Jane",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "pretzel_11"
   },
   {
    "slug": "pretzel_12",
    "name": "Kosher Salt",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "pretzel_12"
   },
   {
    "slug": "pretzel_13",
    "name": "Olive Oil",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "pretzel_13"
   },
   {
    "slug": "pretzel_14",
    "name": "Black Pepper",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "pretzel_14"
   },
   {
    "slug": "pretzel_15",
    "name": "Ranch Dusted",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "pretzel_15"
   },
   {
    "slug": "pretzel_16",
    "name": "Italian Herb",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "pretzel_16"
   },
   {
    "slug": "pretzel_17",
    "name": "Smoked Paprika",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "pretzel_17"
   },
   {
    "slug": "pretzel_18",
    "name": "Cracked Pepper",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "pretzel_18"
   },
   {
    "slug": "pretzel_19",
    "name": "Honey Mustard",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "pretzel_19"
   },
   {
    "slug": "pretzel_20",
    "name": "Pretzel Bites",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "pretzel_20"
   },
   {
    "slug": "pretzel_21",
    "name": "Cheddar Cheese",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "pretzel_21"
   },
   {
    "slug": "pretzel_22",
    "name": "Cinnamon Sugar",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "pretzel_22"
   },
   {
    "slug": "pretzel_23",
    "name": "Jalapeno Cheddar",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "pretzel_23"
   },
   {
    "slug": "pretzel_24",
    "name": "Pizza Pretzel",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "pretzel_24"
   },
   {
    "slug": "pretzel_25",
    "name": "Chocolate Dipped",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "pretzel_25"
   },
   {
    "slug": "pretzel_26",
    "name": "Buffalo Ranch",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "pretzel_26"
   },
   {
    "slug": "pretzel_27",
    "name": "Maple Bacon",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "pretzel_27"
   },
   {
    "slug": "pretzel_28",
    "name": "Caramel Pecan",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "pretzel_28"
   },
   {
    "slug": "pretzel_29",
    "name": "White Chocolate",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "pretzel_29"
   },
   {
    "slug": "pretzel_30",
    "name": "Peanut Butter",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "pretzel_30"
   },
   {
    "slug": "pretzel_31",
    "name": "BBQ Smokehouse",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "pretzel_31"
   },
   {
    "slug": "pretzel_32",
    "name": "Nutella Stuffed",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "pretzel_32"
   },
   {
    "slug": "pretzel_33",
    "name": "Truffle Parmesan",
    "rarity": 3,
    "flavor": "",
    "variantSlug": "pretzel_33"
   },
   {
    "slug": "pretzel_34",
    "name": "Lobster Butter",
    "rarity": 3,
    "flavor": "",
    "variantSlug": "pretzel_34"
   },
   {
    "slug": "pretzel_35",
    "name": "Galaxy Glaze",
    "rarity": 3,
    "flavor": "",
    "variantSlug": "pretzel_35"
   },
   {
    "slug": "pretzel_36",
    "name": "Neon Sour",
    "rarity": 3,
    "flavor": "",
    "variantSlug": "pretzel_36"
   },
   {
    "slug": "pretzel_37",
    "name": "Firecracker",
    "rarity": 3,
    "flavor": "",
    "variantSlug": "pretzel_37"
   },
   {
    "slug": "pretzel_38",
    "name": "Aurora Frost",
    "rarity": 3,
    "flavor": "",
    "variantSlug": "pretzel_38"
   },
   {
    "slug": "pretzel_39",
    "name": "Golden Pretzel",
    "rarity": 5,
    "flavor": "",
    "variantSlug": "pretzel_39"
   },
   {
    "slug": "pretzel_40",
    "name": "Diamond Twist",
    "rarity": 5,
    "flavor": "",
    "variantSlug": "pretzel_40"
   }
  ]
 },
 {
  "slug": "night_lights",
  "name": "Night Lights",
  "color": "#2A3F9E",
  "reward": {
   "energy": 200,
   "tickets": 30,
   "xp": 1000,
   "title": "Night Navigator"
  },
  "spawn": "time",
  "badge": "flashlight_40",
  "items": [
   {
    "slug": "flashlight_01",
    "name": "Aqua Scout Light",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "flashlight_01"
   },
   {
    "slug": "flashlight_02",
    "name": "Coral Scout Light",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "flashlight_02"
   },
   {
    "slug": "flashlight_03",
    "name": "Violet Scout Light",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "flashlight_03"
   },
   {
    "slug": "flashlight_04",
    "name": "Lime Scout Light",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "flashlight_04"
   },
   {
    "slug": "flashlight_05",
    "name": "Gold Scout Light",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "flashlight_05"
   },
   {
    "slug": "flashlight_06",
    "name": "Aqua Starfinder Light",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "flashlight_06"
   },
   {
    "slug": "flashlight_07",
    "name": "Coral Starfinder Light",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "flashlight_07"
   },
   {
    "slug": "flashlight_08",
    "name": "Violet Starfinder Light",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "flashlight_08"
   },
   {
    "slug": "flashlight_09",
    "name": "Lime Starfinder Light",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "flashlight_09"
   },
   {
    "slug": "flashlight_10",
    "name": "Gold Starfinder Light",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "flashlight_10"
   },
   {
    "slug": "flashlight_11",
    "name": "Aqua Moonbeam Light",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "flashlight_11"
   },
   {
    "slug": "flashlight_12",
    "name": "Coral Moonbeam Light",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "flashlight_12"
   },
   {
    "slug": "flashlight_13",
    "name": "Violet Moonbeam Light",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "flashlight_13"
   },
   {
    "slug": "flashlight_14",
    "name": "Lime Moonbeam Light",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "flashlight_14"
   },
   {
    "slug": "flashlight_15",
    "name": "Gold Moonbeam Light",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "flashlight_15"
   },
   {
    "slug": "flashlight_16",
    "name": "Aqua Wave Rider Light",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "flashlight_16"
   },
   {
    "slug": "flashlight_17",
    "name": "Coral Wave Rider Light",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "flashlight_17"
   },
   {
    "slug": "flashlight_18",
    "name": "Violet Wave Rider Light",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "flashlight_18"
   },
   {
    "slug": "flashlight_19",
    "name": "Lime Wave Rider Light",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "flashlight_19"
   },
   {
    "slug": "flashlight_20",
    "name": "Gold Wave Rider Light",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "flashlight_20"
   },
   {
    "slug": "flashlight_21",
    "name": "Aqua Compass Light",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "flashlight_21"
   },
   {
    "slug": "flashlight_22",
    "name": "Coral Compass Light",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "flashlight_22"
   },
   {
    "slug": "flashlight_23",
    "name": "Violet Compass Light",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "flashlight_23"
   },
   {
    "slug": "flashlight_24",
    "name": "Lime Compass Light",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "flashlight_24"
   },
   {
    "slug": "flashlight_25",
    "name": "Gold Compass Light",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "flashlight_25"
   },
   {
    "slug": "flashlight_26",
    "name": "Aqua Shark Fin Light",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "flashlight_26"
   },
   {
    "slug": "flashlight_27",
    "name": "Coral Shark Fin Light",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "flashlight_27"
   },
   {
    "slug": "flashlight_28",
    "name": "Violet Shark Fin Light",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "flashlight_28"
   },
   {
    "slug": "flashlight_29",
    "name": "Lime Shark Fin Light",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "flashlight_29"
   },
   {
    "slug": "flashlight_30",
    "name": "Gold Shark Fin Light",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "flashlight_30"
   },
   {
    "slug": "flashlight_31",
    "name": "Aqua Movie Magic Light",
    "rarity": 3,
    "flavor": "",
    "variantSlug": "flashlight_31"
   },
   {
    "slug": "flashlight_32",
    "name": "Coral Movie Magic Light",
    "rarity": 3,
    "flavor": "",
    "variantSlug": "flashlight_32"
   },
   {
    "slug": "flashlight_33",
    "name": "Violet Movie Magic Light",
    "rarity": 3,
    "flavor": "",
    "variantSlug": "flashlight_33"
   },
   {
    "slug": "flashlight_34",
    "name": "Lime Movie Magic Light",
    "rarity": 3,
    "flavor": "",
    "variantSlug": "flashlight_34"
   },
   {
    "slug": "flashlight_35",
    "name": "Gold Movie Magic Light",
    "rarity": 3,
    "flavor": "",
    "variantSlug": "flashlight_35"
   },
   {
    "slug": "flashlight_36",
    "name": "Aqua Royal Glow Light",
    "rarity": 3,
    "flavor": "",
    "variantSlug": "flashlight_36"
   },
   {
    "slug": "flashlight_37",
    "name": "Coral Royal Glow Light",
    "rarity": 4,
    "flavor": "",
    "variantSlug": "flashlight_37"
   },
   {
    "slug": "flashlight_38",
    "name": "Violet Royal Glow Light",
    "rarity": 4,
    "flavor": "",
    "variantSlug": "flashlight_38"
   },
   {
    "slug": "flashlight_39",
    "name": "Lime Royal Glow Light",
    "rarity": 4,
    "flavor": "",
    "variantSlug": "flashlight_39"
   },
   {
    "slug": "flashlight_40",
    "name": "Gold Royal Glow Light",
    "rarity": 5,
    "flavor": "",
    "variantSlug": "flashlight_40"
   }
  ]
 },
 {
  "slug": "rain_parade",
  "name": "Rain Parade",
  "color": "#1D9BF0",
  "reward": {
   "energy": 200,
   "tickets": 30,
   "xp": 1000,
   "title": "Rain Parade Captain"
  },
  "spawn": "always",
  "badge": "umbrella_40",
  "items": [
   {
    "slug": "umbrella_01",
    "name": "Aqua Bubble Umbrella",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "umbrella_01"
   },
   {
    "slug": "umbrella_02",
    "name": "Coral Bubble Umbrella",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "umbrella_02"
   },
   {
    "slug": "umbrella_03",
    "name": "Violet Bubble Umbrella",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "umbrella_03"
   },
   {
    "slug": "umbrella_04",
    "name": "Lime Bubble Umbrella",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "umbrella_04"
   },
   {
    "slug": "umbrella_05",
    "name": "Gold Bubble Umbrella",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "umbrella_05"
   },
   {
    "slug": "umbrella_06",
    "name": "Aqua Star Umbrella",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "umbrella_06"
   },
   {
    "slug": "umbrella_07",
    "name": "Coral Star Umbrella",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "umbrella_07"
   },
   {
    "slug": "umbrella_08",
    "name": "Violet Star Umbrella",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "umbrella_08"
   },
   {
    "slug": "umbrella_09",
    "name": "Lime Star Umbrella",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "umbrella_09"
   },
   {
    "slug": "umbrella_10",
    "name": "Gold Star Umbrella",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "umbrella_10"
   },
   {
    "slug": "umbrella_11",
    "name": "Aqua Cloud Umbrella",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "umbrella_11"
   },
   {
    "slug": "umbrella_12",
    "name": "Coral Cloud Umbrella",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "umbrella_12"
   },
   {
    "slug": "umbrella_13",
    "name": "Violet Cloud Umbrella",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "umbrella_13"
   },
   {
    "slug": "umbrella_14",
    "name": "Lime Cloud Umbrella",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "umbrella_14"
   },
   {
    "slug": "umbrella_15",
    "name": "Gold Cloud Umbrella",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "umbrella_15"
   },
   {
    "slug": "umbrella_16",
    "name": "Aqua Wave Umbrella",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "umbrella_16"
   },
   {
    "slug": "umbrella_17",
    "name": "Coral Wave Umbrella",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "umbrella_17"
   },
   {
    "slug": "umbrella_18",
    "name": "Violet Wave Umbrella",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "umbrella_18"
   },
   {
    "slug": "umbrella_19",
    "name": "Lime Wave Umbrella",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "umbrella_19"
   },
   {
    "slug": "umbrella_20",
    "name": "Gold Wave Umbrella",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "umbrella_20"
   },
   {
    "slug": "umbrella_21",
    "name": "Aqua Compass Umbrella",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "umbrella_21"
   },
   {
    "slug": "umbrella_22",
    "name": "Coral Compass Umbrella",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "umbrella_22"
   },
   {
    "slug": "umbrella_23",
    "name": "Violet Compass Umbrella",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "umbrella_23"
   },
   {
    "slug": "umbrella_24",
    "name": "Lime Compass Umbrella",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "umbrella_24"
   },
   {
    "slug": "umbrella_25",
    "name": "Gold Compass Umbrella",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "umbrella_25"
   },
   {
    "slug": "umbrella_26",
    "name": "Aqua Shark Fin Umbrella",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "umbrella_26"
   },
   {
    "slug": "umbrella_27",
    "name": "Coral Shark Fin Umbrella",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "umbrella_27"
   },
   {
    "slug": "umbrella_28",
    "name": "Violet Shark Fin Umbrella",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "umbrella_28"
   },
   {
    "slug": "umbrella_29",
    "name": "Lime Shark Fin Umbrella",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "umbrella_29"
   },
   {
    "slug": "umbrella_30",
    "name": "Gold Shark Fin Umbrella",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "umbrella_30"
   },
   {
    "slug": "umbrella_31",
    "name": "Aqua Castle Umbrella",
    "rarity": 3,
    "flavor": "",
    "variantSlug": "umbrella_31"
   },
   {
    "slug": "umbrella_32",
    "name": "Coral Castle Umbrella",
    "rarity": 3,
    "flavor": "",
    "variantSlug": "umbrella_32"
   },
   {
    "slug": "umbrella_33",
    "name": "Violet Castle Umbrella",
    "rarity": 3,
    "flavor": "",
    "variantSlug": "umbrella_33"
   },
   {
    "slug": "umbrella_34",
    "name": "Lime Castle Umbrella",
    "rarity": 3,
    "flavor": "",
    "variantSlug": "umbrella_34"
   },
   {
    "slug": "umbrella_35",
    "name": "Gold Castle Umbrella",
    "rarity": 3,
    "flavor": "",
    "variantSlug": "umbrella_35"
   },
   {
    "slug": "umbrella_36",
    "name": "Aqua Rainbow Umbrella",
    "rarity": 3,
    "flavor": "",
    "variantSlug": "umbrella_36"
   },
   {
    "slug": "umbrella_37",
    "name": "Coral Rainbow Umbrella",
    "rarity": 4,
    "flavor": "",
    "variantSlug": "umbrella_37"
   },
   {
    "slug": "umbrella_38",
    "name": "Violet Rainbow Umbrella",
    "rarity": 4,
    "flavor": "",
    "variantSlug": "umbrella_38"
   },
   {
    "slug": "umbrella_39",
    "name": "Lime Rainbow Umbrella",
    "rarity": 4,
    "flavor": "",
    "variantSlug": "umbrella_39"
   },
   {
    "slug": "umbrella_40",
    "name": "Gold Rainbow Umbrella",
    "rarity": 5,
    "flavor": "",
    "variantSlug": "umbrella_40"
   }
  ]
 },
 {
  "slug": "camera_crew",
  "name": "Camera Crew",
  "color": "#FF6F61",
  "reward": {
   "energy": 250,
   "tickets": 30,
   "xp": 1200,
   "title": "Camera Crew Captain"
  },
  "spawn": "always",
  "badge": "camera_40",
  "items": [
   {
    "slug": "camera_01",
    "name": "Aqua Scout Camera",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "camera_01"
   },
   {
    "slug": "camera_02",
    "name": "Coral Scout Camera",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "camera_02"
   },
   {
    "slug": "camera_03",
    "name": "Violet Scout Camera",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "camera_03"
   },
   {
    "slug": "camera_04",
    "name": "Lime Scout Camera",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "camera_04"
   },
   {
    "slug": "camera_05",
    "name": "Gold Scout Camera",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "camera_05"
   },
   {
    "slug": "camera_06",
    "name": "Aqua Star Shot Camera",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "camera_06"
   },
   {
    "slug": "camera_07",
    "name": "Coral Star Shot Camera",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "camera_07"
   },
   {
    "slug": "camera_08",
    "name": "Violet Star Shot Camera",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "camera_08"
   },
   {
    "slug": "camera_09",
    "name": "Lime Star Shot Camera",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "camera_09"
   },
   {
    "slug": "camera_10",
    "name": "Gold Star Shot Camera",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "camera_10"
   },
   {
    "slug": "camera_11",
    "name": "Aqua Sunset Camera",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "camera_11"
   },
   {
    "slug": "camera_12",
    "name": "Coral Sunset Camera",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "camera_12"
   },
   {
    "slug": "camera_13",
    "name": "Violet Sunset Camera",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "camera_13"
   },
   {
    "slug": "camera_14",
    "name": "Lime Sunset Camera",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "camera_14"
   },
   {
    "slug": "camera_15",
    "name": "Gold Sunset Camera",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "camera_15"
   },
   {
    "slug": "camera_16",
    "name": "Aqua Wave Rider Camera",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "camera_16"
   },
   {
    "slug": "camera_17",
    "name": "Coral Wave Rider Camera",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "camera_17"
   },
   {
    "slug": "camera_18",
    "name": "Violet Wave Rider Camera",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "camera_18"
   },
   {
    "slug": "camera_19",
    "name": "Lime Wave Rider Camera",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "camera_19"
   },
   {
    "slug": "camera_20",
    "name": "Gold Wave Rider Camera",
    "rarity": 1,
    "flavor": "",
    "variantSlug": "camera_20"
   },
   {
    "slug": "camera_21",
    "name": "Aqua Castle Camera",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "camera_21"
   },
   {
    "slug": "camera_22",
    "name": "Coral Castle Camera",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "camera_22"
   },
   {
    "slug": "camera_23",
    "name": "Violet Castle Camera",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "camera_23"
   },
   {
    "slug": "camera_24",
    "name": "Lime Castle Camera",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "camera_24"
   },
   {
    "slug": "camera_25",
    "name": "Gold Castle Camera",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "camera_25"
   },
   {
    "slug": "camera_26",
    "name": "Aqua Shark Fin Camera",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "camera_26"
   },
   {
    "slug": "camera_27",
    "name": "Coral Shark Fin Camera",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "camera_27"
   },
   {
    "slug": "camera_28",
    "name": "Violet Shark Fin Camera",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "camera_28"
   },
   {
    "slug": "camera_29",
    "name": "Lime Shark Fin Camera",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "camera_29"
   },
   {
    "slug": "camera_30",
    "name": "Gold Shark Fin Camera",
    "rarity": 2,
    "flavor": "",
    "variantSlug": "camera_30"
   },
   {
    "slug": "camera_31",
    "name": "Aqua Fireworks Camera",
    "rarity": 3,
    "flavor": "",
    "variantSlug": "camera_31"
   },
   {
    "slug": "camera_32",
    "name": "Coral Fireworks Camera",
    "rarity": 3,
    "flavor": "",
    "variantSlug": "camera_32"
   },
   {
    "slug": "camera_33",
    "name": "Violet Fireworks Camera",
    "rarity": 3,
    "flavor": "",
    "variantSlug": "camera_33"
   },
   {
    "slug": "camera_34",
    "name": "Lime Fireworks Camera",
    "rarity": 3,
    "flavor": "",
    "variantSlug": "camera_34"
   },
   {
    "slug": "camera_35",
    "name": "Gold Fireworks Camera",
    "rarity": 3,
    "flavor": "",
    "variantSlug": "camera_35"
   },
   {
    "slug": "camera_36",
    "name": "Aqua Golden Ticket Camera",
    "rarity": 3,
    "flavor": "",
    "variantSlug": "camera_36"
   },
   {
    "slug": "camera_37",
    "name": "Coral Golden Ticket Camera",
    "rarity": 4,
    "flavor": "",
    "variantSlug": "camera_37"
   },
   {
    "slug": "camera_38",
    "name": "Violet Golden Ticket Camera",
    "rarity": 4,
    "flavor": "",
    "variantSlug": "camera_38"
   },
   {
    "slug": "camera_39",
    "name": "Lime Golden Ticket Camera",
    "rarity": 4,
    "flavor": "",
    "variantSlug": "camera_39"
   },
   {
    "slug": "camera_40",
    "name": "Gold Golden Ticket Camera",
    "rarity": 5,
    "flavor": "",
    "variantSlug": "camera_40"
   }
  ]
 }
];
